### ISSUE TITLE
Preload video

### ISSUE THREAD

**Issue by markuspaschi** [RandyWei/flt_video_player#2]
Good job with the library so far :)

One feature request would be preloading videos. (HLS). 
Would be greatly appreciated.

Greetings Markus

**Comment by RandyWei** [comment]
the TXVodPlayer support preloading videos, this is the documents:https://cloud.tencent.com/document/product/881/20211#step-10.3A-.E9.A2.84.E5.8A.A0.E8.BD.BD
you can customize PlayerConfig and set autoPlay property when use the flt_video_player library.
my english is so so. sorry!
