### ISSUE TITLE
能不能在优化一下大小呢？

### ISSUE THREAD

**Issue by Seifon** [RandyWei/flt_video_player#4]
集成后，发现体积增大了14MB，这个有点吓人了

**Comment by RandyWei** [comment]
这个跟TxVodPlayer SDK有关系，SDK本身集成了很多框架，比如exoPlayer ijkPlayer,而且还要支持各个CPU架构的，我们原生接入这个腾讯云播放器的时候，也是很大的。尽量试试。

**Comment by Seifon** [comment]
能不能单独提取出来呢，想自己去掉一些x86架构的包

你可以参考一下七牛播放器，它好像就是提取了腾讯云lib包自己再封装的

**Comment by RandyWei** [comment]
我提交了一个新版本。弃用aar的方式，包里面没有包含X86的。
