### ISSUE TITLE
ios视频播放偶尔会崩溃

### ISSUE THREAD

**Issue by ietf626** [RandyWei/flt_video_player#9]
ios视频播放偶尔会崩溃，麻烦老哥帮忙解决下，谢谢。

![WX20190722-161411](https://user-images.githubusercontent.com/20748250/61618393-50fc4b80-ac9f-11e9-8644-3156ae75e134.png)

**Comment by xenobe** [comment]
我也遇到这个问题， 请大佬有空更新一下， 谢谢谢谢~

**Comment by RandyWei** [comment]
有视频地址么？之前开发过程中出现过这个问题。研究了ijk的flutter代码，处理掉了。我们这边测试没再出现问题。主要是内存泄露。

**Comment by ietf626** [comment]
这个好像跟视频关系不大，同样的视频有时候会出现，而且就ios会出现异常。

**Comment by RandyWei** [comment]
提交了一个新版本
使用flt_video_player: ^0.0.4

**Comment by ietf626** [comment]
感谢楼主

**Comment by xenobe** [comment]
感谢@RandyWei.  我们测试的时候发现如果同时在一个page上播放多个视频，就容易报错， 新版本我们测试一下， 再次感谢更新。
